### ISSUE TITLE
Fails to build on odin dev-2023-05

### ISSUE THREAD

**Issue by creikey** [colrdavidson/spall-web#23]
Here is the error:
```
C:\Users\Cameron\Documents\spall>python build.py
Compiling...
Failed to execute command:
        "C:\Users\Cameron\Documents\odin\odin\\bin\wasm-ld" "C:/Users/Cameron/Documents/spall/build/spall.wasm.o" -o "C:/Users/Cameron/Documents/spall/build/spall.wasm"  --allow-undefined  --import-memory --initial-memory=131072000 --max-memory=4294967296
Traceback (most recent call last):
  File "C:\Users\Cameron\Documents\spall\build.py", line 43, in <module>
    subprocess.run([
  File "C:\Users\Cameron\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['odin', 'build', 'src', '-collection:formats=formats', '-target:js_wasm32', '-target-features:+bulk-memory', '-extra-linker-flags:--import-memory --initial-memory=131072000 --max-memory=4294967296', '-out:build/spall.wasm', '-debug']' returned non-zero exit status 4294967295.
```

Is there an intended odin compiler version?

**Comment by colrdavidson** [comment]
That's odd. I tend to build on Odin:master, or near it. It builds fine for me, although I'm building on Linux.

Does an older version of the Odin compiler, like dev-2023-04, have the same issue?
